[theme]
# Inherit from Streamlit's built-in light or dark theme
base = "light"  # or "dark"

# Core colors
primaryColor = "#094507"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"